services:
  - type: web
    name: buspass_project
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn buspass_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: buspass_project.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: true
      - key: DATABASE_URL
        sync: true